title:
logo: "/images/logo.jpg?raw=true"
description: > vicky johnson-dahl<br>
  cartographer, dc
  <br>  
  <br>
  <a href="https://www.twitter.com/hurricanevicky/">twitter</a> // <a href="mailto:victoria.johnson@gmail.com?subject=drums!!!">email</a> 
  <br>
  
theme: jekyll-theme-minimal
google_analytics: G-L5954F2CFC # your Google Analytics tracking ID here
